version: '3.8'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app-container
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: BREf+1y?vl
      DB_DATABASE: AdopetiDB
    networks:
      - app-network
    restart: always

networks:
  app-network:
