version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Adopeti123
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network
    restart: always

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app-container
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Adopeti123
      DB_DATABASE: AdopetiDB
    networks:
      - app-network
    restart: always

networks:
  app-network:
